name: Deploy Frontend

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: SSH Deploy
      uses: appleboy/ssh-action@v0.1.7

      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}

        script: |
          cd /home/ubuntu/frontend-app

          git pull origin main
          npm install
          npm run build

          sudo systemctl restart nginx
